LIBTIFF_SRC_LOCATION = /usr/src/libtiff-Release-v4-0-6/libtiff

loadtiff.o: loadtiff.c
	#1. complete this line to compile loadtiff using afl-gcc.

loadtiff: loadtiff.o
	#2. complete this line to compile loadtiff using afl-g++.

clean:
	rm -f *.o
	rm loadtiff

